strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
      imageName: 'windows-latest'

trigger:
- master

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK (based on global.json)'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    installationPath: $(Agent.ToolsDirectory)/dotnet
- bash: ./cibuild.sh
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'cibuild.sh'
- powershell: .\cibuild.cmd
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'cibuild.cmd'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: 'testResults/TestResults-*.xml' 
    mergeTestResults: true

## For publishing stuff, eventually
#
# env:
#   mapped-gh-token: $(xplotpackages)